### ISSUE TITLE
1.16.4 Stable with v1.3.6 petAI and v1.2.6 feverstonehorses : Gen 1 doesnt stay on baby foals when maturing into stallion or mare

### ISSUE THREAD

**Issue by Aledark789** [Ahrondus/VS_Horse#13]
1.16.4 stable
1.3.6 PetAI
1.2.6 feverstonehorses

New world

Enclosed a mare + stallion in a fenced pen.
Only gains portions thru manual feeding even if 100% obedience and tamed.
Eventually mare gives birth to baby foals however...
once they mature to mare or stallion they loose their gen tag.
![2022-03-06_13-28-37](https://user-images.githubusercontent.com/31166271/156938719-aba39daf-fa6f-4bde-9551-71b73c458576.png)
![2022-03-06_13-35-59](https://user-images.githubusercontent.com/31166271/156938720-6356ccd2-064b-4cf4-aecf-f3386a7f900c.png)

Reproduced everytime for baby1, baby2, baby3 and baby4.
Some evolved in stallion some into mare, applied to all of them.

**Comment by Ahrondus** [comment]
Resolved
