### ISSUE TITLE
1.16.4 Stable with v1.3.6 petAI and v1.2.6 feverstonehorses : in F5 mode the name tag above the horse jitters as we move.

### ISSUE THREAD

**Issue by Aledark789** [Ahrondus/VS_Horse#17]
1.16.4 Stable with v1.3.6 petAI and v1.2.6 feverstonehorses : in F5 mode the name of the horses jitters as we move.

I believe Tyron added some code for that in the Mount if i understand it right look at:
https://discord.com/channels/302152934249070593/454909656230526976/931186273002082416

https://github.com/tyronx/mountablesample/blob/main/mods-dll/mountablesample/EntityBoat.cs

**Comment by Ahrondus** [comment]
Resolved
