### ISSUE TITLE
1.16.4 and 1.2.6 horse mod : Add the tamable % in the window UI when you mouse over the horse when trying to tame it. Atm only obedience shows but you need 100% tamed before obedience rises.

### ISSUE THREAD

**Issue by Aledark789** [Ahrondus/VS_Horse#19]
1.16.4 and 1.2.6 horse mod : Add the tamable % in the window UI when you mouse over the horse when trying to tame it. Atm only obedience shows but you need 100% tamed before obedience rises. Does show in the chat but i think it'd make it more clear in the other window and only show obedience for tamed ones.

Should also perhaps not give ownership of horse until its 100% tamed? just wondering.

If horse is in a claim can someone without claim access tame it? Probably shouldnt be able to.

**Comment by Ahrondus** [comment]
1. A creature should not become obedient during taming. The point is to domesticate it (tame it), then have it learn and listen to commands (obedience).
2. "Ownership" during taming just designates the current player that is attempting to tame the creature. No player properly "owns" a horse until taming is complete.
3. A wild horse has no ties to a claim. That would be like saying you can't kill a wild ram inside someone else's claim. The claim owner has no rights over a wild creature, and it shouldn't be restricting any interactions from other players.

**Comment by Aledark789** [comment]
Nod i meant showing "taming" % in the UI window up top before obediance. not just in the chat as you tame it.
